clear baseFileName
clear c
clear er
clear FinalResultsHeader
clear fullFileName

clear G1all
clear G1allcell
clear G1amp
clear G1ampavg
clear G1amphigherr
clear G1amplowerr
clear G1avg
clear G1avgcell
clear G1avgcellwithheader
clear G1avgmax
clear G1avgmin
clear G1avgtimecell
clear G1cell
clear G1data
clear G1errhigh
clear G1errlow
clear G1finalresultscellavg
clear G1finalresultsheader
clear G1idx
clear G1minidx
clear G1sem
clear G1semcell
clear G1semcellwithheader
clear G1semplot
clear G1semtest
clear G1std
clear G1stdcell
clear G1stdcellwithheader
clear G1stderr
clear G1stdplot
clear G1stdtest

clear G2all
clear G2allcell
clear G2amp
clear G2ampavg
clear G2amphigherr
clear G2amplowerr
clear G2avg
clear G2avgcell
clear G2avgcellwithheader
clear G2avgmax
clear G2avgmin
clear G2avgtimecell
clear G2cell
clear G2data
clear G2errhigh
clear G2errlow
clear G2finalresultscellavg
clear G2finalresultsheader
clear G2idx
clear G2minidx
clear G2sem
clear G2semcell
clear G2semcellwithheader
clear G2semplot
clear G2semtest
clear G2std
clear G2stdcell
clear G2stdcellwithheader
clear G2stderr
clear G2stdplot
clear G2stdtest

clear gnames
clear Gstderr
clear h
clear idx
clear k
clear m
clear M
clear myDir
clear myFiles
clear n
clear p
clear Tfold
clear Tfoldcell
clear Tfoldcellwithheader
clear Twave
clear x
clear Groupstats
clear GroupstatsHeader
clear Groupstatscell
clear G1ampevenfinal
clear ampL
clear G1ampL
clear G1evenamp
clear G1nanadd
clear G2ampevenfinal
clear G2ampL
clear maxampL